### ISSUE TITLE
Circular reference

### ISSUE THREAD

**Issue by moueza** [Homniserv/spring-webflow-2#4]
http://localhost:9225/spring-webflow-2/greeting22

Etat HTTP 500 - Circular view path [greeting22]: would dispatch back to the current handler URL [/spring-webflow-2/greeting22] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

type Rapport d''exception

message Circular view path [greeting22]: would dispatch back to the current handler URL [/spring-webflow-2/greeting22] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)

description Le serveur a rencontré une erreur interne qui l''a empêché de satisfaire la requête.

exception 
javax.servlet.ServletException: Circular view path [greeting22]: would dispatch back to the current handler URL [/spring-webflow-2/greeting22] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
	org.springframework.web.servlet.view.InternalResourceView.prepareForRendering(InternalResourceView.java:205)
	org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:145)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
	org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

note La trace complète de la cause mère de cette erreur est disponible dans les fichiers journaux de Apache Tomcat/7.0.85.

Apache Tomcat/7.0.85

**Comment by moueza** [comment]
Console

> juin 13, 2018 9:34:07 AM org.apache.tomcat.util.digester.SetPropertiesRule begin
AVERTISSEMENT: [SetPropertiesRule]{Server/Service/Engine/Host/Context} Setting property 'source' to 'org.eclipse.jst.j2ee.server:spring-webflow-2' did not find a matching property.
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server version:        Apache Tomcat/7.0.85
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server built:          Feb 7 2018 18:52:33 UTC
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Server number:         7.0.85.0
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Name:               Windows 10
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: OS Version:            10.0
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Architecture:          amd64
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Java Home:             C:\Program Files\Java\jdk1.8.0_131\jre
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Version:           1.8.0_131-b11
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: JVM Vendor:            Oracle Corporation
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_BASE:         C:\Users\mouez\workspace-sts-3.9.4.RELEASE\.metadata\.plugins\org.eclipse.wst.server.core\tmp6
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: CATALINA_HOME:         C:\Users\mouez\apache-tomcat-7.0.85-windows-x64\apache-tomcat-7.0.85
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dcatalina.base=C:\Users\mouez\workspace-sts-3.9.4.RELEASE\.metadata\.plugins\org.eclipse.wst.server.core\tmp6
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dcatalina.home=C:\Users\mouez\apache-tomcat-7.0.85-windows-x64\apache-tomcat-7.0.85
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dwtp.deploy=C:\Users\mouez\workspace-sts-3.9.4.RELEASE\.metadata\.plugins\org.eclipse.wst.server.core\tmp6\wtpwebapps
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Djava.endorsed.dirs=C:\Users\mouez\apache-tomcat-7.0.85-windows-x64\apache-tomcat-7.0.85\endorsed
juin 13, 2018 9:34:07 AM org.apache.catalina.startup.VersionLoggerListener log
INFOS: Command line argument: -Dfile.encoding=Cp1252
juin 13, 2018 9:34:07 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFOS: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: C:\Program Files\Java\jdk1.8.0_131\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:/Program Files/Java/jre1.8.0_151/bin/server;C:/Program Files/Java/jre1.8.0_151/bin;C:/Program Files/Java/jre1.8.0_151/lib/amd64;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program Files (x86)\Symantec\VIP Access Client\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\mouez\AppData\Local\Microsoft\WindowsApps;;C:\Users\mouez\spring-tool-suite-3.9.4.RELEASE-e4.7.3a-win32-x86_64\sts-bundle\sts-3.9.4.RELEASE;;.
juin 13, 2018 9:34:08 AM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["http-bio-9225"]
juin 13, 2018 9:34:09 AM org.apache.coyote.AbstractProtocol init
INFOS: Initializing ProtocolHandler ["ajp-bio-8010"]
juin 13, 2018 9:34:09 AM org.apache.catalina.startup.Catalina load
INFOS: Initialization processed in 4840 ms
juin 13, 2018 9:34:09 AM org.apache.catalina.core.StandardService startInternal
INFOS: Démarrage du service Catalina
juin 13, 2018 9:34:09 AM org.apache.catalina.core.StandardEngine startInternal
INFOS: Starting Servlet Engine: Apache Tomcat/7.0.85
juin 13, 2018 9:34:18 AM org.apache.catalina.startup.TldConfig execute
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
juin 13, 2018 9:34:19 AM org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
AVERTISSEMENT: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [606] milliseconds.
juin 13, 2018 9:34:29 AM org.apache.catalina.startup.TldConfig execute
INFOS: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
juin 13, 2018 9:34:29 AM org.apache.catalina.core.ApplicationContext log
INFOS: No Spring WebApplicationInitializer types detected on classpath
juin 13, 2018 9:34:29 AM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring root WebApplicationContext
juin 13, 2018 9:34:29 AM org.springframework.web.context.ContextLoader initWebApplicationContext
INFOS: Root WebApplicationContext: initialization started
juin 13, 2018 9:34:30 AM org.springframework.web.context.support.XmlWebApplicationContext prepareRefresh
INFOS: Refreshing Root WebApplicationContext: startup date [Wed Jun 13 09:34:30 CEST 2018]; root of context hierarchy
juin 13, 2018 9:34:30 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFOS: Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContextMoi.xml]
juin 13, 2018 9:34:32 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFOS: Mapped "{[/greeting22],methods=[GET]}" onto public java.lang.String hello.AnnotGreeting2Controller.greeting(java.lang.String,org.springframework.ui.Model)
juin 13, 2018 9:34:32 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping register
INFOS: Mapped "{[/hello]}" onto public org.springframework.web.servlet.ModelAndView hello.AnnotGreeting4Controller.helloWorld()
juin 13, 2018 9:34:32 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter initControllerAdviceCache
INFOS: Looking for @ControllerAdvice: Root WebApplicationContext: startup date [Wed Jun 13 09:34:30 CEST 2018]; root of context hierarchy
juin 13, 2018 9:34:32 AM org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter initControllerAdviceCache
INFOS: Looking for @ControllerAdvice: Root WebApplicationContext: startup date [Wed Jun 13 09:34:30 CEST 2018]; root of context hierarchy
juin 13, 2018 9:34:33 AM org.springframework.web.context.ContextLoader initWebApplicationContext
INFOS: Root WebApplicationContext: initialization completed in 3436 ms
juin 13, 2018 9:34:33 AM org.apache.catalina.core.ApplicationContext log
INFOS: Initializing Spring FrameworkServlet 'example'
juin 13, 2018 9:34:33 AM org.springframework.web.servlet.DispatcherServlet initServletBean
INFOS: FrameworkServlet 'example': initialization started
juin 13, 2018 9:34:33 AM org.springframework.web.context.support.XmlWebApplicationContext prepareRefresh
INFOS: Refreshing WebApplicationContext for namespace 'example-servlet': startup date [Wed Jun 13 09:34:33 CEST 2018]; parent: Root WebApplicationContext
juin 13, 2018 9:34:33 AM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFOS: Loading XML bean definitions from ServletContext resource [/WEB-INF/example-servlet.xml]
juin 13, 2018 9:34:33 AM org.springframework.web.servlet.DispatcherServlet initServletBean
INFOS: FrameworkServlet 'example': initialization completed in 149 ms
juin 13, 2018 9:34:33 AM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["http-bio-9225"]
juin 13, 2018 9:34:33 AM org.apache.coyote.AbstractProtocol start
INFOS: Starting ProtocolHandler ["ajp-bio-8010"]
juin 13, 2018 9:34:33 AM org.apache.catalina.startup.Catalina start
INFOS: Server startup in 24289 ms
juin 13, 2018 9:34:35 AM org.springframework.web.servlet.PageNotFound noHandlerFound
AVERTISSEMENT: No mapping found for HTTP request with URI [/spring-webflow-2/] in DispatcherServlet with name 'example'
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
09:34:45.855 [http-bio-9225-exec-4] ERROR hello.AnnotGreeting2Controller - in greeting22 2
juin 13, 2018 9:34:45 AM org.apache.catalina.core.StandardWrapperValve invoke
GRAVE: Servlet.service() for servlet [example] in context with path [/spring-webflow-2] threw exception [Circular view path [greeting22]: would dispatch back to the current handler URL [/spring-webflow-2/greeting22] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)] with root cause
javax.servlet.ServletException: Circular view path [greeting22]: would dispatch back to the current handler URL [/spring-webflow-2/greeting22] again. Check your ViewResolver setup! (Hint: This may be the result of an unspecified view, due to default view name generation.)
	at org.springframework.web.servlet.view.InternalResourceView.prepareForRendering(InternalResourceView.java:205)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:145)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
